### ISSUE TITLE
Thread Action Delete Posting with Patch Method

### ISSUE THREAD

**Issue by whmackay** [Riari/laravel-forum-frontend#10]
I think I have this problem correct. In **Laravel-Forum-Frontend 1.0.3** when selecting the `'delete'` action from the `thread.partials.show blade` it attempts to post using **_method patch instead of delete**. Out of the box that doesn't appear to be supported since the request will be routed to `ThreadController@update` which doesn't have a means for handling destroy requests. I'm brand new to working with Laravel so could be missing something, but at the moment to fix the issue for myself I copied the destroy function in the update function and added some steering logic based on the `request->input('action')`. Is this an issue or misunderstanding?

**[Work Around]***

```
public function update(Request $request)
    {
        $action = $request->input('action');

        if ($action == 'delete')
        {
            $this->validate($request, ['action' => 'in:delete,permadelete']);

            $permanent = !config('forum.preferences.soft_deletes') || ($request->input('action') == 'permadelete');

            $parameters = $request->all();

            if ($permanent) {
                $parameters += ['force' => 1];
            }

            $thread = $this->api('thread.delete', $request->route('thread'))->parameters($parameters)->delete();

            Forum::alert('success', 'threads.deleted', 1);            
            return redirect($permanent ? Forum::route('category.show', $thread->category) : Forum::route('thread.show', $thread));
        }
        else
        {
            $thread = $this->api("thread.{$action}", $request->route('thread'))->parameters($request->all())->patch();
            Forum::alert('success', 'threads.updated', 1);
            return redirect(Forum::route('thread.show', $thread));
        }
    }
```

**Comment by whmackay** [comment]
Same problem seems to apply to the Category delete action. Same work around applied to the CategoryController resolved it for me. I intend to try to fix it in the *.show.blade since I have to customize those anyhow to theme them properly for my website instead of changing functional libraries.

**Comment by Riari** [comment]
The method is supposed to change to `delete` dynamically when you select one of the delete options. This depends on the JS in the default [master view](https://github.com/Riari/laravel-forum-frontend/blob/1.0/views/master.blade.php) and uses the `data-method` attribute on the select options.
