### ISSUE TITLE
error in view "Undefined variable: errors"

### ISSUE THREAD

**Issue by texnika01** [Riari/laravel-forum-frontend#11]
I have a problem with : 
Undefined variable: errors (View: D:\Xampp\htdocs\Test.dev\resources\views\vendor\forum\partials\alerts.blade.php) (View: D:\Xampp\htdocs\Test.dev\resources\views\vendor\forum\partials\alerts.blade.php) (View: D:\Xampp\htdocs\Test.dev\resources\views\vendor\forum\partials\alerts.blade.php)

**Comment by Riari** [comment]
Assuming you're using Laravel 5.2, you need to set your `forum.frontend.middleware` config value to `web`.

**Comment by texnika01** [comment]
Ok.I will try
