### ISSUE TITLE
Way to Customize where Views are loaded from

### ISSUE THREAD

**Issue by g33kidd** [Riari/laravel-forum-frontend#13]
Pretty self-explanitory. I was wanting to move the views into my views root folder and modify the forum design from there. Is this planned or is there a way I can do this currently?

**Comment by Riari** [comment]
I don't think this is possible as the path is determined by Laravel. There might be a way to override it via the service provider, but I don't know for certain. Otherwise, the best thing you can do is probably to move the views to where you want them and create a symlink to them.
