### ISSUE TITLE
Error occured during category deletion

### ISSUE THREAD

**Issue by roastedfrost-zz** [Riari/laravel-forum-frontend#14]
Seems to be a wrong config parameter is used in appropriate route
_forum.routing.root_ instead of _forum.routing.prefix_

``` php
    public function destroy(Request $request)
    {
        $this->api('category.delete', $request->route('category'))->parameters($request->all())->delete();
        Forum::alert('success', 'categories.deleted', 1);
        return redirect(config('forum.routing.root'));
    }
```

**Comment by Riari** [comment]
Thanks for the heads up. There are a few redirects using that old config value - I've just pushed a release to correct them both.
