### ISSUE TITLE
Config not compatible with cache:config

### ISSUE THREAD

**Issue by esseremmerik** [Riari/laravel-forum-frontend#2]
Hello @Riari 

It seems like the frontend package is not compatible with the config:cache functionality of Laravel. It still contains a function in the config, which is not allowed.

See https://github.com/Riari/laravel-forum-frontend/blob/1.0/config/frontend.php#L33-L47

**Comment by Riari** [comment]
Thanks, I wasn't aware of this. I'm going to make some changes soon that should hopefully do away with that function.

**Comment by esseremmerik** [comment]
Great, thanks. If you look at your https://github.com/Riari/laravel-forum/tree/laravel-5 (2.0), your configs contain a lot more functions so 3.0 is a big improvement on this part already. But if you want to make 2.0 compatible as well, you might want to take a look at these configs.

**Comment by Riari** [comment]
Yeah, I'll most likely leave those alone as it would be a much bigger issue to change them, especially in terms of the permission callbacks, which many people are guaranteed to have overridden already.

**Comment by Riari** [comment]
Addressed in https://github.com/Riari/laravel-forum-frontend/releases/tag/1.0.1. Thanks again.
