### ISSUE TITLE
Frontend does not work with laravel-forum 4.1

### ISSUE THREAD

**Issue by inkvizytor** [Riari/laravel-forum-frontend#22]
When I run composer update I see this message:
riari/laravel-forum-frontend 1.1.6 requires riari/laravel-forum 3.0 - 4.0 -> satisfiable by riari/laravel-forum[3.0.x-dev, 4.0.x-dev].
I think changing required version in composer.json will solve the problem.

**Comment by Riari** [comment]
Thanks for the heads up. New release specifies the correct version range.
