### ISSUE TITLE
URL slugify not support none ascii character

### ISSUE THREAD

**Issue by charlespeng** [Riari/laravel-forum-frontend#23]
Hi,
slugify() function in src/Support/Forum.php uses Laravel helper function str_slug() which will remove none ascii character, so we can not use none ASCII (UTF8) character in category title or thread title.

For now, I use the solution from [here](https://stackoverflow.com/questions/23238849/create-url-slugs-for-chinese-characters-using-php) to quick fix this issue.

Is there better way to solve this issue ?

**Comment by Riari** [comment]
I intentionally leave this up to the user - the support class is designed to be overridden in cases like this, so you can implement slug generation however you like. See the [utility_class config option](https://github.com/Riari/laravel-forum-frontend/blob/1.0/config/frontend.php#L58).

**Comment by charlespeng** [comment]
Thanks a lot
