### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by Riari** [Riari/laravel-forum-frontend#28]
Also as part of this:

- [ ] Improve appearance and mobile support
- [ ] Replace jQuery code with Vue
- [ ] Implement "edit category structure" mode for re-ordering of categories

**Comment by Gummibeer** [comment]
Using Vue is laravel pattern but will make it more difficult for oldschool pages or other SPA frameworks.
For me this package is, except the controller, no "ready to use" but more a demo one. And as this it should keep as simple as possible - Vue will add a new complexity that not everyone can follow/will understand.

It could be that I'm alone with this - if so I'm fine with Vue!

**Comment by Riari** [comment]
Yeah, I wasn't 100% sure about whether to use Vue, but my plan is to only use it to replace the jQuery and handle the category re-ordering. It should be pretty minimal overall and I want to keep the Vue code as simple as possible - if I manage to do that, it should be worth it.

I'll probably also update the docs to explain a bit more about the provided JS and what features depend on it.

**Comment by Riari** [comment]
Closing this since laravel-forum 5.0 will ship with its own frontend.
