### ISSUE TITLE
Add prefix for routes

### ISSUE THREAD

**Issue by antonkomarev** [Riari/laravel-forum-frontend#6]
Could you make `'as' => 'forum.',` routing group prefix configurable in future?

Not a really important thing, it's mostly for naming consistency. For example I've got in one of the projects prefixes for frontend part as `fe.articles`, `fe.news` and want to use `fe.forums` without disabling package routes and copying them manually.

**Comment by Riari** [comment]
Will consider this for the next release :)

**Comment by Riari** [comment]
Addressed in the latest releases.
